env: devnet
urls:
  mxApi: 'https://devnet-api.multiversx.com/'
  swagger:
    - 'http://localhost:3000/'
    - 'https://devnet-microservice.multiversx.com'
    - 'https://testnet-microservice.multiversx.com'
    - 'https://microservice.multiversx.com'
  redis: '127.0.0.1'
  rabbitMqUrl: 'amqp://localhost:5672'
security:
  jwtSecret: ''
